spring:
  profiles: local
orientdb:
  url: http://localhost:2480/
  user: root
  password: R3k&Do1ps
  database: Tangela

---

spring:
  profiles: prod
orientdb:
  url: http://localhost:2480/
  user: root
  password: Sq2FPS3La
  database: Tangela
